# Site settings
title: Robin Young
email: test@gmail.com
description:
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: United States of America
phone:

icon: fa-mountain-sun # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/rbnyng
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed